# Generated by Django 4.1.3 on 2022-11-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='username',
            new_name='user',
        ),
    ]
