FROM node:16.18.1

WORKDIR /usr/app

COPY package.json .
RUN yarn install

COPY . .
RUN yarn run build

RUN apt-get update && apt-get install -y nginx
COPY nginx.conf /etc/nginx/sites-available/nginx.conf
RUN rm /etc/nginx/sites-enabled/default
RUN ln -s /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled/nginx.conf
RUN mkdir -p /usr/share/nginx/html
RUN cp -r build/* /usr/share/nginx/html/

RUN mkdir -p ssl