# Generated by Django 4.1.2 on 2022-11-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_updated_alter_user_created'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('number', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField()),
                ('free', models.BooleanField()),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_group', to='users.user')),
                ('members', models.ManyToManyField(related_name='group', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_element', models.ManyToManyField(related_name='group_goal', to='workouts.fitelement')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='groups.group')),
            ],
        ),
    ]
