# Generated by Django 4.1.3 on 2022-11-24 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('number', models.IntegerField(null=True)),
                ('member_number', models.IntegerField(default=0)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField()),
                ('free', models.BooleanField()),
                ('goal', models.ManyToManyField(related_name='group_goal', to='workouts.fitelement')),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_group', to='users.user')),
                ('members', models.ManyToManyField(related_name='group', to='users.user')),
            ],
        ),
    ]
