# Generated by Django 4.1.3 on 2022-11-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_tag_tag_type"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_groups", to="tags.tag"
            ),
        ),
    ]
