# Generated by Django 4.1.2 on 2022-11-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='goal',
            field=models.ManyToManyField(related_name='group_goal', to='workouts.fitelement'),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
