# Generated by Django 4.1.2 on 2022-11-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_goal_delete_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_number',
            field=models.IntegerField(default=0),
        ),
    ]
