# Generated by Django 4.1.3 on 2022-11-27 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_tag_tag_type"),
        ("groups", "0002_group_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="prime_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prime_tagged_groups",
                to="tags.tag",
            ),
        ),
    ]
