# Generated by Django 4.1.2 on 2022-11-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_member_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='group',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
