# Generated by Django 4.1.2 on 2022-11-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_joinrequest'),
        ('groups', '0003_group_prime_tag'),
    ]

    operations = [
    ]
