# Generated by Django 4.1.2 on 2022-11-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('users', '0003_user_updated_alter_user_created'),
        ('groups', '0004_alter_group_options_group_address_group_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fit_element', models.ManyToManyField(blank=True, to='workouts.fitelement')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cert', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cert', to='users.user')),
            ],
        ),
    ]
