# Generated by Django 4.1.3 on 2022-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_message_group_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='new1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='new2',
            field=models.BooleanField(default=False),
        ),
    ]
