# Generated by Django 4.1.3 on 2022-11-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0004_chatroom_new1_chatroom_new2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='recent_message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
