# Generated by Django 4.1.3 on 2022-11-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0005_chatroom_recent_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='recent_message',
            field=models.CharField(default='(최근 메시지)', max_length=255),
        ),
    ]
