# Generated by Django 4.1.3 on 2022-11-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_tagclass_class_type"),
        ("informations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="tag",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to="tags.tag",
            ),
            preserve_default=False,
        ),
    ]
