# Generated by Django 4.1.3 on 2022-11-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_tagclass_class_type"),
        ("informations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="information",
            name="article_info",
        ),
        migrations.RemoveField(
            model_name="information",
            name="youtube_info",
        ),
        migrations.AddField(
            model_name="information",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to="tags.tag",
            ),
        ),
        migrations.AddField(
            model_name="youtubecontent",
            name="channel",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="youtubecontent",
            name="information",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="youtube",
                to="informations.information",
            ),
        ),
        migrations.AddField(
            model_name="youtubecontent",
            name="published",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="youtubecontent",
            name="thumbnail",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="youtubecontent",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="youtubecontent",
            name="video_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
