# Generated by Django 4.1.2 on 2022-11-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created",)},
        ),
        migrations.RemoveField(
            model_name="post",
            name="dislike_num",
        ),
        migrations.RemoveField(
            model_name="post",
            name="like_num",
        ),
        migrations.RemoveField(
            model_name="post",
            name="scrap_num",
        ),
        migrations.AddField(
            model_name="post",
            name="disliker",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_posts", to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="liker",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="scraper",
            field=models.ManyToManyField(
                blank=True, related_name="scraped_posts", to="users.user"
            ),
        ),
    ]
