# Generated by Django 4.1.3 on 2022-12-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_merge_0002_joinrequest_0003_group_prime_tag"),
        ("workouts", "0007_rename_index_dailylog_log_index"),
        ("posts", "0002_post_in_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tagged_posts",
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="routine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tagged_posts",
                to="workouts.routine",
            ),
        ),
    ]
