# Generated by Django 4.1.3 on 2022-11-04 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options'),
        ('posts', '0002_alter_post_options_remove_post_dislike_num_and_more'),
    ]

    operations = [
    ]
