# Generated by Django 4.1.2 on 2022-11-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_rename_name_tag_tag_name_and_more"),
        ("posts", "0003_merge_20221102_2341"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_posts", to="tags.tag"
            ),
        ),
    ]
