# Generated by Django 4.1.3 on 2022-11-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_merge_20221104_0135'),
        ('posts', '0004_post_tags'),
    ]

    operations = [
    ]
