# Generated by Django 4.1.3 on 2022-11-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_rename_name_tag_tag_name_and_more"),
        ("posts", "0005_merge_0003_merge_20221104_0135_0004_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="prime_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prime_tagged_posts",
                to="tags.tag",
            ),
        ),
    ]
