# Generated by Django 4.1.3 on 2022-12-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(max_length=30)),
                ('class_type', models.CharField(choices=[('general', 'General'), ('workout', 'Workout'), ('place', 'Place')], default='general', max_length=20)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(max_length=10)),
                ('tag_type', models.CharField(choices=[('general', 'General'), ('workout', 'Workout'), ('place', 'Place')], default='general', max_length=20)),
                ('calories', models.FloatField(null=True)),
                ('tag_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tags.tagclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
