# Generated by Django 4.1.3 on 2022-12-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="tagclass",
            name="class_name",
            field=models.CharField(max_length=20),
        ),
    ]
