# Generated by Django 4.1.3 on 2022-11-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("workout", "Workout"),
                    ("place", "Place"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
