# Generated by Django 4.1.2 on 2022-11-03 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_alter_tag_tag_class"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="tag_name",
        ),
        migrations.RenameField(
            model_name="tagclass",
            old_name="string",
            new_name="class_name",
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="tags.tagclass",
            ),
        ),
    ]
