# Generated by Django 4.1.3 on 2022-11-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_rename_name_tag_tag_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagclass",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("workout", "Workout"),
                    ("place", "Place"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
