# Generated by Django 4.1.3 on 2022-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_tagclass_class_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="calories",
            field=models.FloatField(null=True),
        ),
    ]
