# Generated by Django 4.1.3 on 2022-11-22 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('goal', 'goal'), ('log', 'log')], max_length=4)),
                ('workout_type', models.CharField(max_length=30)),
                ('period', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('rep', models.IntegerField(null=True)),
                ('set', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_element', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='FitElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('korean_name', models.CharField(max_length=120, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('arm', 'arm'), ('leg', 'leg'), ('back', 'back'), ('chest', 'chest'), ('deltoid', 'deltoid'), ('abs', 'abs'), ('etc', 'etc')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('calories', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='users.user')),
                ('fit_element', models.ManyToManyField(blank=True, to='workouts.fitelement')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.TextField(null=True)),
                ('calories', models.IntegerField(default=0, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_log', to='users.user')),
                ('fit_element', models.ManyToManyField(blank=True, to='workouts.fitelement')),
            ],
        ),
    ]
