# Generated by Django 4.1.3 on 2022-11-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitelementtype',
            name='korean_name',
        ),
        migrations.AlterField(
            model_name='fitelementtype',
            name='category',
            field=models.CharField(choices=[('arm', 'arm'), ('leg', 'leg'), ('back', 'back'), ('chest', 'chest'), ('deltoid', 'deltoid'), ('abs', 'abs'), ('cardio', 'cardio'), ('etc', 'etc')], max_length=10),
        ),
    ]
