# Generated by Django 4.1.3 on 2022-11-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('calories', models.IntegerField()),
                ('category', models.CharField(choices=[('arm', 'arm'), ('leg', 'leg'), ('back', 'back'), ('chest', 'chest'), ('deltoid', 'deltoid'), ('abs', 'abs'), ('etc', 'etc')], max_length=10)),
            ],
        ),
    ]
