# Generated by Django 4.1.3 on 2022-11-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_delete_fitelementtype_remove_fitelement_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workouts.dailylog')),
            ],
        ),
    ]
