# Generated by Django 4.1.3 on 2022-11-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_dailylogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='image',
        ),
    ]
