# Generated by Django 4.1.3 on 2022-11-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_fitelementtype_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='calories',
            field=models.IntegerField(null=True),
        ),
    ]
