# Generated by Django 4.1.3 on 2022-11-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_dailylog_calories_routine_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='calories',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
