# Generated by Django 4.1.3 on 2022-11-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_remove_dailylog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailylog",
            name="calories",
            field=models.FloatField(default=0, null=True),
        ),
    ]
