# Generated by Django 4.1.3 on 2022-11-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_alter_dailylog_calories"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="index",
            field=models.TextField(null=True),
        ),
    ]
