# Generated by Django 4.1.3 on 2022-11-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_dailylog_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailylog",
            old_name="index",
            new_name="log_index",
        ),
    ]
