# Generated by Django 4.1.2 on 2022-11-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("comments", "0003_alter_comment_parent_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dislike_num",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="like_num",
        ),
        migrations.AddField(
            model_name="comment",
            name="disliker",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_comments", to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="liker",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="scraper",
            field=models.ManyToManyField(
                blank=True, related_name="scraped_comments", to="users.user"
            ),
        ),
    ]
