# Generated by Django 4.1.2 on 2022-10-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('hashed_password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=8)),
                ('image', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
    ]
