# Generated by Django 4.1.3 on 2022-11-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('login_method', models.CharField(choices=[('email', 'Email'), ('kakao', 'Kakao'), ('github', 'Github'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', max_length=20)),
                ('validated', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=20)),
                ('hashed_password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=8)),
                ('image', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('level', models.IntegerField()),
                ('follower', models.ManyToManyField(blank=True, related_name='+', to='users.user')),
                ('following', models.ManyToManyField(blank=True, related_name='+', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
