# Generated by Django 4.1.2 on 2022-10-30 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
