# Generated by Django 4.1.3 on 2022-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_login_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="validated",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("kakao", "Kakao"),
                    ("github", "Github"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
